### ISSUE TITLE
data/googleplaystore.csv

### ISSUE THREAD

**Issue by Bramminator** [gerkovink/INFOMDA1-2021#2]
Hey, 

Another question... You mention in the practical you have already downloaded the file mentioned above. However I have no idea where to find it. Where is the data map? Is it on github or on your site? I can't find it...

**Comment by DepressionRegression** [comment]
Hello, 

It's Kevin from the course. I am having the same issue, except with the next file, which is students.xlxs. I cannot seem to find this or 01_Data_Wrangling.Rproj listed in the beginning.  If you need access to the googleplaystore.csv, you can download it directly from Kaggle. I have already done so, so I will attach them to this answer. 
[googleplaystore.csv](https://github.com/gerkovink/INFOMDA1-2021/files/7142985/googleplaystore.csv)
[googleplaystore_user_reviews.csv](https://github.com/gerkovink/INFOMDA1-2021/files/7142986/googleplaystore_user_reviews.csv)

**Comment by Bramminator** [comment]
Hey, I saw I could download it with an account, but did want to make a Kaggle account, so I thank you for providing me with the data.

**Comment by DepressionRegression** [comment]
Did you have any luck regarding the project file I mentioned or the next data set (students.xlxs)? I am not sure if I am missing something. I did check the course website and BB. I also sent the professor a message on Teams (which I forgot I was not supposed to do - whoops _sweating emoji_.

**Comment by Bramminator** [comment]
No, I stopped when I couldnt find the first file. But I have found no folder on either teams or the site with a datafile, despite searching a while. Let's wait until mr Vink replies, yesterday he did within two hours.

**Comment by DepressionRegression** [comment]
Hey Bramm,

Dr. Vink just informed me that all should be okay now if you refresh the page!

**Comment by gerkovink** [comment]
Indeed. And please call me Gerko 😉
